### PR TITLE
Improve build page

### PR DESCRIPTION
**Pull request by Holzhaus**
- Improves the look (personal opinion)
- Moves the `<script>` stuff into the head tag (and specifies `type="text/javasscript"`)
- Uses the simple `<noscript>` tag for the "You don't have Javascript" error message

### CODE REVIEW

**Comment by Holzhaus** [comment]
Screenshot:
Screenshot

That thing at the bottom left is from my WM, not from the page ;-)

**Comment by skmp** [comment]
I've modified the dns so it's now served from gh-pages

**Comment by Holzhaus** [comment]
Cool. Would be nice if I could get push access.

**Comment by skmp** [comment]
Hrfm, I had to manually add the teams to the repos. Weird. You should have commit access now :)

**Comment by Holzhaus** [comment]
Thanks. :+1:

**Pull request merged**
